//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer.KiemThe.MxDatabaseController
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiemTheMixDbEntities : DbContext
    {
        public KiemTheMixDbEntities()
            : base("name=KiemTheMixDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleParamInt> RoleParamInts { get; set; }
        public virtual DbSet<RoleParamString> RoleParamStrings { get; set; }
    }
}
