//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer.KiemThe.MxDatabaseController
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleParamString
    {
        public int RoleID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public string ParamValue { get; set; }
    }
}
